# Generated by Django 5.1.8 on 2026-03-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_portfolio_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='template_id',
            field=models.CharField(choices=[('minimal', 'Minimal Developer Template'), ('dark', 'Dark Developer Theme'), ('cards', 'Modern Card Layout'), ('professional', 'Professional Template'), ('creative', 'Creative Template'), ('terminal', 'Hacker CLI Terminal'), ('robotic', 'Cyberpunk Robotic Mode')], default='minimal', max_length=20),
        ),
    ]
